// <auto-generated />
using EmployeeDataWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDataWebAPI.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDataWebAPI.Model.Employee1", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_id"));

                    b.Property<string>("emp_lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_id");

                    b.ToTable("Employees1");

                    b.HasData(
                        new
                        {
                            emp_id = 300,
                            emp_lang = "C#",
                            emp_name = "Anu"
                        },
                        new
                        {
                            emp_id = 301,
                            emp_lang = "C",
                            emp_name = "Mohit"
                        },
                        new
                        {
                            emp_id = 302,
                            emp_lang = "Java",
                            emp_name = "Sona"
                        },
                        new
                        {
                            emp_id = 303,
                            emp_lang = "Java",
                            emp_name = "Lana"
                        },
                        new
                        {
                            emp_id = 304,
                            emp_lang = "C#",
                            emp_name = "Lion"
                        },
                        new
                        {
                            emp_id = 305,
                            emp_lang = "Java",
                            emp_name = "Ramona"
                        });
                });

            modelBuilder.Entity("EmployeeDataWebAPI.Model.Employee2", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_id"));

                    b.Property<string>("emp_dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emp_salary")
                        .HasColumnType("int");

                    b.HasKey("emp_id");

                    b.ToTable("Employees2");

                    b.HasData(
                        new
                        {
                            emp_id = 300,
                            emp_dept = "Designing",
                            emp_salary = 23000
                        },
                        new
                        {
                            emp_id = 301,
                            emp_dept = "Developing",
                            emp_salary = 40000
                        },
                        new
                        {
                            emp_id = 302,
                            emp_dept = "HR",
                            emp_salary = 50000
                        },
                        new
                        {
                            emp_id = 303,
                            emp_dept = "Designing",
                            emp_salary = 60000
                        },
                        new
                        {
                            emp_id = 403,
                            emp_dept = "Production",
                            emp_salary = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
